import type { OnModuleInit } from '@nestjs/common';
import { Inject, Injectable, Logger } from '@nestjs/common';
import { SkillVerificationCompletedEventSchema, HIREKIWI_TOPICS } from '@hirekiwi/contracts';
import { runKafkaHandler } from '@hirekiwi/observability';
import { env } from '../../platform/config/env.js';
import { KafkaService } from '../../platform/kafka/kafka.service.js';
import { CandidateEmbeddingService } from './candidate-embedding.service.js';

/**
 * Keeps a candidate's Stage 1 embedding (CandidateEmbeddingService) from going stale: whenever a
 * skill claim is newly VERIFIED, the student's verified-skills profile text has changed, so the
 * embedding built from it is now out of date. Mirrors SkillVerificationCorroborationConsumer's
 * subscription pattern. Before this, candidate embeddings only ever regenerated by manually
 * running backfill-candidate-embeddings.ts — job embeddings already auto-refresh on
 * create/update/publish (employer-jobs.service.ts), this closes the matching gap candidate-side.
 */
@Injectable()
export class CandidateEmbeddingRefreshConsumer implements OnModuleInit {
  private readonly logger = new Logger(CandidateEmbeddingRefreshConsumer.name);

  constructor(
    @Inject(KafkaService) private readonly kafka: KafkaService,
    @Inject(CandidateEmbeddingService) private readonly embedding: CandidateEmbeddingService,
  ) {}

  async onModuleInit(): Promise<void> {
    if (env.NODE_ENV === 'test') return;
    try {
      await this.kafka.subscribe({
        topic: HIREKIWI_TOPICS.skillVerificationCompleted,
        module: 'matching-candidate-embedding-refresh',
        handler: async (payload, headers) => {
          await runKafkaHandler(headers, async () => {
            const parsed = SkillVerificationCompletedEventSchema.safeParse(payload);
            if (!parsed.success) {
              this.logger.warn(
                'Ignored malformed skill.verification.completed for embedding refresh',
              );
              return;
            }

            const event = parsed.data.data;
            if (event.status !== 'VERIFIED') return;

            try {
              await this.embedding.generateAndStoreEmbedding(event.userId);
            } catch (error) {
              // Never blocks the event / other consumers on an embedding provider hiccup — the
              // next backfill run (or next verification event) picks it up.
              this.logger.warn(
                `Candidate embedding refresh failed for ${event.userId}: ${error instanceof Error ? error.message : 'unknown'}`,
              );
            }
          });
        },
      });
    } catch (error) {
      this.logger.warn(
        `candidate embedding refresh consumer not started: ${error instanceof Error ? error.message : 'unknown'}`,
      );
    }
  }
}
