/**
 * AUTO-GENERATED from tools/content-pipeline/data/taxonomies/skill.json
 * Source: docs/Global_IT_Skills_Database.xlsx (Category + Skill columns)
 * Regenerate: pnpm --filter @smart/content-pipeline codegen:skill
 * DO NOT EDIT MANUALLY.
 */

import {
  DEFAULT_COMPETENCY_BARS,
  levels,
  type LevelThreshold,
  type ProficiencyLevel,
} from './skill-levels.js';

export const SKILL_TAXONOMY_VERSION = 'skill@1' as const;
export const SKILL_TAXONOMY_DOMAINS = ['SOFTWARE_IT'] as const;
export type SkillTaxonomyDomain = (typeof SKILL_TAXONOMY_DOMAINS)[number];

export const SKILL_CATEGORY_IDS = [
  'PROGRAMMING_LANGUAGES',
  'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
  'CLOUD_PLATFORMS',
  'DEVOPS_INFRASTRUCTURE',
  'DATABASES_DATA_MANAGEMENT',
  'DATA_ENGINEERING_BIG_DATA',
  'AI_ML_DATA_SCIENCE',
  'CYBERSECURITY',
  'TESTING_QA_RELIABILITY',
  'MOBILE_DEVELOPMENT',
  'FRONTEND_WEB_DEVELOPMENT',
  'NETWORKING_SYSTEMS_ADMINISTRATION',
  'EMERGING_TECHNOLOGY',
  'DELIVERY_PROCESS_TOOLING',
] as const;
export type SkillCategoryId = (typeof SKILL_CATEGORY_IDS)[number];

export const SKILL_CATEGORIES: Readonly<
  Record<SkillCategoryId, { readonly id: SkillCategoryId; readonly name: string }>
> = {
  PROGRAMMING_LANGUAGES: { id: 'PROGRAMMING_LANGUAGES', name: 'Programming Languages' },
  SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN: {
    id: 'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    name: 'Software Architecture & System Design',
  },
  CLOUD_PLATFORMS: { id: 'CLOUD_PLATFORMS', name: 'Cloud Platforms' },
  DEVOPS_INFRASTRUCTURE: { id: 'DEVOPS_INFRASTRUCTURE', name: 'DevOps & Infrastructure' },
  DATABASES_DATA_MANAGEMENT: {
    id: 'DATABASES_DATA_MANAGEMENT',
    name: 'Databases & Data Management',
  },
  DATA_ENGINEERING_BIG_DATA: {
    id: 'DATA_ENGINEERING_BIG_DATA',
    name: 'Data Engineering & Big Data',
  },
  AI_ML_DATA_SCIENCE: { id: 'AI_ML_DATA_SCIENCE', name: 'AI, ML & Data Science' },
  CYBERSECURITY: { id: 'CYBERSECURITY', name: 'Cybersecurity' },
  TESTING_QA_RELIABILITY: { id: 'TESTING_QA_RELIABILITY', name: 'Testing, QA & Reliability' },
  MOBILE_DEVELOPMENT: { id: 'MOBILE_DEVELOPMENT', name: 'Mobile Development' },
  FRONTEND_WEB_DEVELOPMENT: { id: 'FRONTEND_WEB_DEVELOPMENT', name: 'Frontend & Web Development' },
  NETWORKING_SYSTEMS_ADMINISTRATION: {
    id: 'NETWORKING_SYSTEMS_ADMINISTRATION',
    name: 'Networking & Systems Administration',
  },
  EMERGING_TECHNOLOGY: { id: 'EMERGING_TECHNOLOGY', name: 'Emerging Technology' },
  DELIVERY_PROCESS_TOOLING: { id: 'DELIVERY_PROCESS_TOOLING', name: 'Delivery, Process & Tooling' },
};

export interface SkillDefinition {
  readonly code: string;
  readonly name: string;
  readonly categoryId: SkillCategoryId;
  readonly categoryName: string;
  readonly domain: SkillTaxonomyDomain;
  readonly levels: Readonly<Record<ProficiencyLevel, LevelThreshold>>;
  readonly corroborationEligible: boolean;
  readonly assessmentRequiredForClaim: boolean;
}

function entry(
  code: string,
  name: string,
  categoryId: SkillCategoryId,
  categoryName: string,
): SkillDefinition {
  return {
    code,
    name,
    categoryId,
    categoryName,
    domain: 'SOFTWARE_IT',
    levels: levels(DEFAULT_COMPETENCY_BARS),
    corroborationEligible: true,
    assessmentRequiredForClaim: true,
  };
}

export const SKILL_DEFINITIONS: readonly SkillDefinition[] = [
  entry('ABAP', 'ABAP', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ADA', 'Ada', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('AKKA', 'Akka', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ALAMOFIRE', 'Alamofire', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('AMPSCRIPT', 'AMPscript', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APACHE_ACTIVEMQ', 'Apache ActiveMQ', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APACHE_ANT', 'Apache Ant', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APACHE_CAMEL', 'Apache Camel', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APACHE_CXF', 'Apache CXF', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'APACHE_HTTP_SERVER',
    'Apache HTTP Server',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('APACHE_SUPERSET', 'Apache Superset', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APACHE_THRIFT', 'Apache Thrift', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APACHE_TOMCAT', 'Apache Tomcat', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APEX', 'Apex', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APIGEE', 'Apigee', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('APOLLO_CLIENT', 'Apollo Client', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ASP_DOTNET', 'ASP.NET', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ASP_DOTNET_CORE', 'ASP.NET Core', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ASSEMBLY', 'Assembly', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('AURA_COMPONENTS', 'Aura Components', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('AUTORABIT', 'AutoRabit', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('AXUM', 'Axum', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BASH', 'Bash', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BITRISE', 'Bitrise', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BLAZOR', 'Blazor', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BOKEH', 'Bokeh', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BOOMI', 'Boomi', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BUILDKITE', 'Buildkite', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('BUN', 'Bun', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('C_LANGUAGE', 'C', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('C_SHARP', 'C#', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'C_SYSTEMS_PERFORMANCE_ENGINEERING',
    'C++',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('CADDY', 'Caddy', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CAKEPHP', 'CakePHP', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CELERY', 'Celery', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CEPH', 'Ceph', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CILIUM', 'Cilium', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CLANG', 'Clang', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CLAUDE_CODE', 'Claude Code', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CLOJURE', 'Clojure', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('COCOAPODS', 'CocoaPods', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CODEIGNITER', 'CodeIgniter', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('COMBINE', 'Combine', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CONSUL', 'Consul', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('COPADO', 'Copado', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('COVERITY', 'Coverity', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('CURSOR', 'Cursor', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DAGGER', 'Dagger', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DAPPER', 'Dapper', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DART', 'Dart', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DEEPSPEED', 'DeepSpeed', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DENO', 'Deno', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DJANGO', 'Django', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DJANGO_CHANNELS', 'Django Channels', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'DJANGO_REST_FRAMEWORK',
    'Django REST Framework',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('DRONE_CI', 'Drone CI', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DROPWIZARD', 'Dropwizard', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DVC', 'DVC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ECLIPSE', 'Eclipse', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ELIXIR', 'Elixir', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ELM', 'Elm', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('EMBER_JS', 'Ember.js', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ENTITY_FRAMEWORK', 'Entity Framework', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'ENTITY_FRAMEWORK_CORE',
    'Entity Framework Core',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('ERLANG', 'Erlang', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('EXPRESS_JS', 'Express.js', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('EXTJS', 'ExtJS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('F_SHARP', 'F#', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FASTAPI', 'FastAPI', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FASTIFY', 'Fastify', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FIGMA', 'Figma', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FIREBASE', 'Firebase', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'FIREBASE_FIRESTORE',
    'Firebase Firestore',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('FISH', 'Fish', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FLASK', 'Flask', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FORTRAN', 'Fortran', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('FOUNDRY', 'Foundry', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GATSBY', 'Gatsby', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GCC', 'GCC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GEARSET', 'Gearset', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'GO_GOLANG_FOR_HIGH_PERFORMANCE_SERVICES',
    'Go',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('GO_MODULES', 'Go Modules', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'GOOGLE_ARTIFACT_REGISTRY',
    'Google Artifact Registry',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('GOOGLE_BIGTABLE', 'Google Bigtable', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'GOOGLE_COMPUTE_ENGINE',
    'Google Compute Engine',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('GOOGLE_FILESTORE', 'Google Filestore', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'GOOGLE_MEMORYSTORE',
    'Google Memorystore',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('GOOGLE_PUB_SUB', 'Google Pub/Sub', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GRAPHQL', 'GraphQL', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GROOVY', 'Groovy', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GRPC', 'gRPC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GTK', 'GTK', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('GUNICORN', 'Gunicorn', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HARNESS', 'Harness', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HASKELL', 'Haskell', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HAYSTACK', 'Haystack', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HIBERNATE', 'Hibernate', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HILT', 'Hilt', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HONO', 'Hono', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('HOTWIRE', 'Hotwire', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('IBM_MQ', 'IBM MQ', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('IBM_QRADAR', 'IBM QRadar', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('IIS', 'IIS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('INERTIA_JS', 'Inertia.js', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JAKARTA_EE', 'Jakarta EE', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'JAKARTA_PERSISTENCE_JPA',
    'Jakarta Persistence (JPA)',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry(
    'JAVA_ENTERPRISE_APPLICATION_DEVELOPMENT',
    'Java',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('JAVASCRIPT', 'JavaScript', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JBOSS', 'JBoss', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JMOCKIT', 'JMockit', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JQUERY', 'jQuery', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JULIA', 'Julia', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JUPYTER', 'Jupyter', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('JUPYTERLAB', 'JupyterLab', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('KEYCLOAK', 'Keycloak', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('KIBANA', 'Kibana', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('KOIN', 'Koin', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'KOTLIN_FOR_ANDROID_BACKEND_SERVICES',
    'Kotlin',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('KOTLIN_COROUTINES', 'Kotlin Coroutines', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'KOTLIN_MULTIPLATFORM',
    'Kotlin Multiplatform',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('KSERVE', 'KServe', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('KUBEFLOW', 'Kubeflow', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('KUSTOMIZE', 'Kustomize', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LARAVEL', 'Laravel', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'LIGHTNING_WEB_COMPONENTS',
    'Lightning Web Components',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('LINQ', 'LINQ', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LIT', 'Lit', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LIVEWIRE', 'Livewire', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LLVM', 'LLVM', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LOGSTASH', 'Logstash', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LOMBOK', 'Lombok', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LOOKER', 'Looker', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LUA', 'Lua', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LXC', 'LXC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('LXD', 'LXD', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MAPSTRUCT', 'MapStruct', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MATLAB', 'MATLAB', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MATPLOTLIB', 'Matplotlib', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MESON', 'Meson', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('METABASE', 'Metabase', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MICRONAUT', 'Micronaut', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MINIKUBE', 'Minikube', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MOVE', 'Move', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MULESOFT', 'MuleSoft', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('MYBATIS', 'MyBatis', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DOTNET', '.NET', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DOTNET_CORE', '.NET Core', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('DOTNET_MAUI', '.NET MAUI', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('N8N', 'n8n', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NATS', 'NATS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NESTJS', 'NestJS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NETBEANS', 'NetBeans', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NETCAT', 'Netcat', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NGRX', 'NgRx', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NGXS', 'NGXS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NIM', 'Nim', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NODE_JS', 'Node.js', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NOMAD', 'Nomad', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NVIDIA_ISAAC_SIM', 'NVIDIA Isaac Sim', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NVIDIA_NEMO', 'NVIDIA NeMo', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('NVIDIA_NIM', 'NVIDIA NIM', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OBJECTIVE_C', 'Objective-C', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OMNISTUDIO', 'OmniStudio', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENFEIGN', 'OpenFeign', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENFGA', 'OpenFGA', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENSEARCH', 'OpenSearch', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'OPENSEARCH_DASHBOARDS',
    'OpenSearch Dashboards',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('OPENSHIFT', 'OpenShift', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENSTACK', 'OpenStack', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENTOFU', 'OpenTofu', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENWRT', 'OpenWrt', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('OPENZFS', 'OpenZFS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PAGERDUTY', 'PagerDuty', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PARCEL', 'Parcel', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PASSENGER', 'Passenger', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PASSPORT_JS', 'Passport.js', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PENNYLANE', 'PennyLane', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PERFORCE', 'Perforce', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PERL', 'Perl', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PHOENIX', 'Phoenix', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PHP', 'PHP', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PHPUNIT', 'PHPUnit', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PILLOW', 'Pillow', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PLATFORMIO', 'PlatformIO', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PLAY_FRAMEWORK', 'Play Framework', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PLOTLY', 'Plotly', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('POWER_BI', 'Power BI', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('POWERSHELL', 'PowerShell', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('PYRAMID', 'Pyramid', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'PYTHON_APPLICATION_BACKEND_DEVELOPMENT',
    'Python',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('Q_SHARP', 'Q#', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('QLIK_SENSE', 'Qlik Sense', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('QLIKVIEW', 'QlikView', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('QML', 'QML', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('QT', 'Qt', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('QUARKUS', 'Quarkus', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('R_FOR_STATISTICAL_COMPUTING', 'R', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('RABBITMQ', 'RabbitMQ', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('RANCHER', 'Rancher', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('RESILIENCE4J', 'Resilience4j', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('REST_ASSURED', 'REST Assured', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ROCKET', 'Rocket', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ROLLUP', 'Rollup', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ROOM', 'Room', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('RUBY', 'Ruby', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'RUST_FOR_SYSTEMS_RELIABILITY_ENGINEERING',
    'Rust',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('RXSWIFT', 'RxSwift', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SALESFORCE_DATA_CLOUD',
    'Salesforce Data Cloud',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SALESFORCE_DX', 'Salesforce DX', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SALESFORCE_FLOW', 'Salesforce Flow', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SALESFORCE_MARKETING_CLOUD',
    'Salesforce Marketing Cloud',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SALTSTACK', 'SaltStack', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SAP_BTP', 'SAP BTP', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SAP_BUSINESS_APPLICATION_STUDIO',
    'SAP Business Application Studio',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SAP_CAP', 'SAP CAP', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SAP_FIORI', 'SAP Fiori', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SAP_HANA', 'SAP HANA', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SAP_INTEGRATION_SUITE_CPI',
    'SAP Integration Suite (CPI)',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry(
    'SAP_SUCCESSFACTORS',
    'SAP SuccessFactors',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry(
    'SCALA_FOR_DISTRIBUTED_DATA_SYSTEMS',
    'Scala',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SCRAPY', 'Scrapy', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SENTRY', 'Sentry', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SHOPIFY', 'Shopify', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SIDEKIQ', 'Sidekiq', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SINATRA', 'Sinatra', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SNAPLOGIC', 'SnapLogic', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SOLIDITY', 'Solidity', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SOLIDJS', 'SolidJS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SONARQUBE', 'SonarQube', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SOQL', 'SOQL', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SPARX_ENTERPRISE_ARCHITECT',
    'Sparx Enterprise Architect',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SPINNAKER', 'Spinnaker', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SPRING', 'Spring', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SPRING_BATCH', 'Spring Batch', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SPRING_BOOT', 'Spring Boot', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SPRING_CLOUD', 'Spring Cloud', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SPRING_DATA', 'Spring Data', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SPRING_INTEGRATION',
    'Spring Integration',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SPRING_MVC', 'Spring MVC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('SSIS', 'SSIS', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('STRAPI', 'Strapi', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'SWIFT_FOR_IOS_MACOS_DEVELOPMENT',
    'Swift',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry(
    'SWIFT_PACKAGE_MANAGER',
    'Swift Package Manager',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('SYMFONY', 'Symfony', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('TABLEAU', 'Tableau', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('TAURI', 'Tauri', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'TEAM_FOUNDATION_SERVER',
    'Team Foundation Server',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('TENSORBOARD', 'TensorBoard', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('TRAVIS_CI', 'Travis CI', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('TRPC', 'tRPC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('TYPEORM', 'TypeORM', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('TYPESCRIPT', 'TypeScript', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('UVICORN', 'Uvicorn', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('VBA', 'VBA', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('VEEVA', 'Veeva', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('VERT_X', 'Vert.x', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('VISUAL_BASIC', 'Visual Basic', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('VISUALFORCE', 'Visualforce', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('VXWORKS', 'VxWorks', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WCF', 'WCF', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WEBDRIVERIO', 'WebdriverIO', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WEBRTC', 'WebRTC', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WEIGHTS_BIASES', 'Weights & Biases', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WINDOWS_FORMS', 'Windows Forms', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WORDPRESS', 'WordPress', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WORKDAY_STUDIO', 'Workday Studio', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WPF', 'WPF', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('WSO2', 'WSO2', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ZED', 'Zed', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ZEEK', 'Zeek', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ZEROMQ', 'ZeroMQ', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry('ZSH', 'Zsh', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'ASYNCHRONOUS_PROGRAMMING',
    'Asynchronous Programming',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('DATA_ANALYSIS', 'Data Analysis', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'DATA_PREPROCESSING',
    'Data Preprocessing',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('IMAGE_PROCESSING', 'Image Processing', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'MACHINE_LEARNING_MODEL_DEVELOPMENT_DEPLOYMENT',
    'Machine Learning',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('MODEL_EVALUATION', 'Model Evaluation', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'PROMPT_ENGINEERING',
    'Prompt Engineering',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry('REST_APIS', 'REST APIs', 'PROGRAMMING_LANGUAGES', 'Programming Languages'),
  entry(
    'STRUCTURED_OUTPUTS',
    'Structured Outputs',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry(
    'TEXT_CLASSIFICATION',
    'Text Classification',
    'PROGRAMMING_LANGUAGES',
    'Programming Languages',
  ),
  entry(
    'JAX_RS',
    'JAX-RS',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'JAX_WS',
    'JAX-WS',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'JMS',
    'JMS',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'JSON',
    'JSON',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'JSON_RPC',
    'JSON-RPC',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'MARKDOWN',
    'Markdown',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'ODATA',
    'OData',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'OPENACC',
    'OpenACC',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'OPENAPI',
    'OpenAPI',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'OPENMP',
    'OpenMP',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'PROTOCOL_BUFFERS',
    'Protocol Buffers',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'SERVER_SENT_EVENTS',
    'Server-Sent Events',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'SERVICE_WORKERS',
    'Service Workers',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'SOAP',
    'SOAP',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'XML',
    'XML',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'XSLT',
    'XSLT',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'YAML',
    'YAML',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'A2A',
    'A2A',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'AUC_GINI',
    'AUC / Gini',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'AUTOSCALING',
    'Autoscaling',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'CAPTURE_RATE',
    'Capture Rate',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'COST_OPTIMIZATION',
    'Cost Optimization',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'DATA_DRIFT',
    'Data Drift',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'DATA_VERSIONING',
    'Data Versioning',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'DEPTH_SENSING',
    'Depth Sensing',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'DOCUMENT_INTELLIGENCE',
    'Document Intelligence',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'HALLUCINATION_MITIGATION',
    'Hallucination Mitigation',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'INFERENCE_OPTIMIZATION',
    'Inference Optimization',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'K_S_STATISTIC',
    'K-S Statistic',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'KNOWLEDGE_GRAPHS',
    'Knowledge Graphs',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'LATENCY_OPTIMIZATION',
    'Latency Optimization',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'LOW_LATENCY_INFERENCE',
    'Low-Latency Inference',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'MULTILINGUAL_NLP',
    'Multilingual NLP',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'PLANNING_EXECUTION_LOOPS',
    'Planning / Execution Loops',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'QUANTIZATION',
    'Quantization',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry(
    'TOKEN_OPTIMIZATION',
    'Token Optimization',
    'SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN',
    'Software Architecture & System Design',
  ),
  entry('AMAZON_API_GATEWAY', 'Amazon API Gateway', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_AURORA', 'Amazon Aurora', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_BEDROCK', 'Amazon Bedrock', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_CLOUDFORMATION', 'Amazon CloudFormation', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_CLOUDFRONT', 'Amazon CloudFront', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_CLOUDWATCH', 'Amazon CloudWatch', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_COGNITO', 'Amazon Cognito', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_EC2', 'Amazon EC2', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_ECR', 'Amazon ECR', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_ECS', 'Amazon ECS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_EKS', 'Amazon EKS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_EMR', 'Amazon EMR', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_EVENTBRIDGE', 'Amazon EventBridge', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_FSX', 'Amazon FSx', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_KINESIS', 'Amazon Kinesis', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_MSK', 'Amazon MSK', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'AMAZON_OPENSEARCH_SERVICE',
    'Amazon OpenSearch Service',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('AMAZON_RDS', 'Amazon RDS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_ROUTE_53', 'Amazon Route 53', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_S3', 'Amazon S3', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_SAGEMAKER', 'Amazon SageMaker', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_SNS', 'Amazon SNS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_SQS', 'Amazon SQS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AMAZON_VPC', 'Amazon VPC', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_CDK', 'AWS CDK', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_CODEBUILD', 'AWS CodeBuild', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_CODEDEPLOY', 'AWS CodeDeploy', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_CODEPIPELINE', 'AWS CodePipeline', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_CONFIG', 'AWS Config', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_FARGATE', 'AWS Fargate', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_IAM', 'AWS IAM', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_KMS', 'AWS KMS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_LAMBDA', 'AWS Lambda', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_ORGANIZATIONS', 'AWS Organizations', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_STEP_FUNCTIONS', 'AWS Step Functions', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AWS_WAF', 'AWS WAF', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_API_MANAGEMENT', 'Azure API Management', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_APP_SERVICE', 'Azure App Service', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'AZURE_APPLICATION_GATEWAY',
    'Azure Application Gateway',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry(
    'AZURE_APPLICATION_INSIGHTS',
    'Azure Application Insights',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('AZURE_BLOB_STORAGE', 'Azure Blob Storage', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_BOARDS', 'Azure Boards', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_DATA_FACTORY', 'Azure Data Factory', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_DEVOPS', 'Azure DevOps', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_EVENT_GRID', 'Azure Event Grid', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_EVENT_HUBS', 'Azure Event Hubs', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_FRONT_DOOR', 'Azure Front Door', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_FUNCTIONS', 'Azure Functions', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_LOAD_BALANCER', 'Azure Load Balancer', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_LOGIC_APPS', 'Azure Logic Apps', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_MONITOR', 'Azure Monitor', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_PIPELINES', 'Azure Pipelines', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_REPOS', 'Azure Repos', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_RESOURCE_MANAGER', 'Azure Resource Manager', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_SERVICE_BUS', 'Azure Service Bus', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('AZURE_SYNAPSE_ANALYTICS', 'Azure Synapse Analytics', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('FLY_IO', 'Fly.io', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_APP_ENGINE', 'Google App Engine', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'GOOGLE_CLOUD_API_GATEWAY',
    'Google Cloud API Gateway',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('GOOGLE_CLOUD_ARMOR', 'Google Cloud Armor', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_BUILD', 'Google Cloud Build', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_COMPOSER', 'Google Cloud Composer', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'GOOGLE_CLOUD_DATA_FUSION',
    'Google Cloud Data Fusion',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('GOOGLE_CLOUD_DATAFLOW', 'Google Cloud Dataflow', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_DATAPROC', 'Google Cloud Dataproc', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_DNS', 'Google Cloud DNS', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_FUNCTIONS', 'Google Cloud Functions', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_IAM', 'Google Cloud IAM', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'GOOGLE_CLOUD_LOAD_BALANCING',
    'Google Cloud Load Balancing',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('GOOGLE_CLOUD_LOGGING', 'Google Cloud Logging', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_MONITORING', 'Google Cloud Monitoring', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_RUN', 'Google Cloud Run', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_SCHEDULER', 'Google Cloud Scheduler', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_SPANNER', 'Google Cloud Spanner', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_STORAGE', 'Google Cloud Storage', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_TASKS', 'Google Cloud Tasks', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GOOGLE_CLOUD_WORKFLOWS', 'Google Cloud Workflows', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('NETLIFY', 'Netlify', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('VERCEL', 'Vercel', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'AMAZON_WEB_SERVICES_AWS_ARCHITECTURE',
    'Amazon Web Services (AWS)',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('CLOUDFLARE', 'Cloudflare', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'GOOGLE_CLOUD_PLATFORM_GCP_ENGINEERING',
    'Google Cloud Platform (GCP)',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('IBM_CLOUD', 'IBM Cloud', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'MICROSOFT_AZURE_CLOUD_ENGINEERING',
    'Microsoft Azure',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('CLOUD_AI_AWS_AZURE_GCP', 'Cloud AI (AWS/Azure/GCP)', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('CLOUD_DEPLOYMENT', 'Cloud Deployment', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('EXPERIMENT_DESIGN', 'Experiment Design', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('FEATURE_SELECTION', 'Feature Selection', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('FEATURE_STORES', 'Feature Stores', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('FINE_TUNING', 'Fine-tuning', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('FUNCTION_CALLING', 'Function Calling', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GPU_COMPUTING', 'GPU Computing', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('GSTREAMER', 'GStreamer', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('HALLUCINATION_DETECTION', 'Hallucination Detection', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('HUMAN_IN_THE_LOOP', 'Human-in-the-Loop', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'HYPERPARAMETER_OPTIMIZATION',
    'Hyperparameter Optimization',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('IMAGE_CLASSIFICATION', 'Image Classification', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry(
    'MEMORY_STATE_MANAGEMENT',
    'Memory / State Management',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry(
    'NAMED_ENTITY_RECOGNITION',
    'Named Entity Recognition',
    'CLOUD_PLATFORMS',
    'Cloud Platforms',
  ),
  entry('NVIDIA_DEEPSTREAM', 'NVIDIA DeepStream', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('OBJECT_DETECTION', 'Object Detection', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('OCR', 'OCR', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('OUTPUT_VALIDATION', 'Output Validation', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('PRECISION_RECALL', 'Precision / Recall', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('QLORA', 'QLoRA', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('RTSP', 'RTSP', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('TOKENIZATION', 'Tokenization', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('TOOL_CALLING', 'Tool Calling', 'CLOUD_PLATFORMS', 'Cloud Platforms'),
  entry('ANSIBLE', 'Ansible', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('ARGO_CD', 'Argo CD', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('ARGO_WORKFLOWS', 'Argo Workflows', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('ATLANTIS', 'Atlantis', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('AZURE_KEY_VAULT', 'Azure Key Vault', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry(
    'AZURE_KUBERNETES_SERVICE',
    'Azure Kubernetes Service',
    'DEVOPS_INFRASTRUCTURE',
    'DevOps & Infrastructure',
  ),
  entry('BICEP', 'Bicep', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('BUILDAH', 'Buildah', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('CARGO', 'Cargo', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('CHEF', 'Chef', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('CIRCLECI', 'CircleCI', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry(
    'CONFLUENT_PLATFORM',
    'Confluent Platform',
    'DEVOPS_INFRASTRUCTURE',
    'DevOps & Infrastructure',
  ),
  entry(
    'CONFLUENT_SCHEMA_REGISTRY',
    'Confluent Schema Registry',
    'DEVOPS_INFRASTRUCTURE',
    'DevOps & Infrastructure',
  ),
  entry('CROSSPLANE', 'Crossplane', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('DATADOG', 'Datadog', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('DOCKER', 'Docker', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('DOCKER_COMPOSE', 'Docker Compose', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('DYNATRACE', 'Dynatrace', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('ENVOY', 'Envoy', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('FLUENT_BIT', 'Fluent Bit', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('FLUENTD', 'Fluentd', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('FLUX', 'Flux', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('FLUXCD', 'FluxCD', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('GITHUB_ACTIONS', 'GitHub Actions', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('GITLAB_CI_CD', 'GitLab CI/CD', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry(
    'GOOGLE_KUBERNETES_ENGINE',
    'Google Kubernetes Engine',
    'DEVOPS_INFRASTRUCTURE',
    'DevOps & Infrastructure',
  ),
  entry('GRAFANA', 'Grafana', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('GRAFANA_LOKI', 'Grafana Loki', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('GRAFANA_TEMPO', 'Grafana Tempo', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('HAPROXY', 'HAProxy', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('HASHICORP_VAULT', 'HashiCorp Vault', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('HELM', 'Helm', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('ISTIO', 'Istio', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('JAEGER', 'Jaeger', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('JENKINS', 'Jenkins', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('KEDA', 'KEDA', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('KUBERNETES', 'Kubernetes', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('LINKERD', 'Linkerd', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('NEW_RELIC', 'New Relic', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('NGINX', 'Nginx', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('OPENTELEMETRY', 'OpenTelemetry', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('PACKER', 'Packer', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('PODMAN', 'Podman', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('PROMETHEUS', 'Prometheus', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('PULUMI', 'Pulumi', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('PUPPET', 'Puppet', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('PUPPETEER', 'Puppeteer', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('SPLUNK', 'Splunk', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('SPRING_WEBFLUX', 'Spring WebFlux', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('TEKTON', 'Tekton', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('TEMPORAL', 'Temporal', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('TERRAFORM', 'Terraform', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('TERRAGRUNT', 'Terragrunt', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('TRAEFIK', 'Traefik', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('VAGRANT', 'Vagrant', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('ZABBIX', 'Zabbix', 'DEVOPS_INFRASTRUCTURE', 'DevOps & Infrastructure'),
  entry('AEROSPIKE', 'Aerospike', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'AMAZON_DYNAMODB',
    'Amazon DynamoDB',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'AMAZON_ELASTICACHE',
    'Amazon ElastiCache',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'APACHE_CASSANDRA',
    'Apache Cassandra',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'AZURE_CACHE_FOR_REDIS',
    'Azure Cache for Redis',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'AZURE_COSMOS_DB',
    'Azure Cosmos DB',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'AZURE_SQL_DATABASE',
    'Azure SQL Database',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry('CHROMA', 'Chroma', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('CLICKHOUSE', 'ClickHouse', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('COCKROACHDB', 'CockroachDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('COUCHBASE', 'Couchbase', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('COUCHDB', 'CouchDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('DBT', 'dbt', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('DUCKDB', 'DuckDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('ELASTIC_APM', 'Elastic APM', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'ELASTICSEARCH',
    'Elasticsearch',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'GOOGLE_CLOUD_SQL',
    'Google Cloud SQL',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry('H2', 'H2', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('IBM_DB2', 'IBM Db2', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('MARIADB', 'MariaDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('MEMCACHED', 'Memcached', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'MICROSOFT_SQL_SERVER',
    'Microsoft SQL Server',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry('MILVUS', 'Milvus', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('MINIO', 'MinIO', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('MONGODB', 'MongoDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('MYSQL', 'MySQL', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('NEO4J', 'Neo4j', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('ORACLE_APEX', 'Oracle APEX', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'ORACLE_CLOUD_INFRASTRUCTURE',
    'Oracle Cloud Infrastructure',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'ORACLE_DATABASE',
    'Oracle Database',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'ORACLE_INTEGRATION_CLOUD',
    'Oracle Integration Cloud',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry(
    'ORACLE_REST_DATA_SERVICES',
    'Oracle REST Data Services',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry('PINECONE', 'Pinecone', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('PL_SQL', 'PL/SQL', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('POSTGRESQL', 'PostgreSQL', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('QDRANT', 'Qdrant', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('REDIS', 'Redis', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'REDIS_STREAMS',
    'Redis Streams',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry('RETHINKDB', 'RethinkDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('SCYLLADB', 'ScyllaDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'SQL_QUERY_OPTIMIZATION',
    'SQL',
    'DATABASES_DATA_MANAGEMENT',
    'Databases & Data Management',
  ),
  entry('SQLITE', 'SQLite', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('SUPABASE', 'Supabase', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('TIDB', 'TiDB', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('VALKEY', 'Valkey', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry('WEAVIATE', 'Weaviate', 'DATABASES_DATA_MANAGEMENT', 'Databases & Data Management'),
  entry(
    'AMAZON_ATHENA',
    'Amazon Athena',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry(
    'AMAZON_REDSHIFT',
    'Amazon Redshift',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('APACHE_ARROW', 'Apache Arrow', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_ATLAS', 'Apache Atlas', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_AVRO', 'Apache Avro', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_BEAM', 'Apache Beam', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_DRUID', 'Apache Druid', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_FLINK', 'Apache Flink', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_FLUME', 'Apache Flume', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'APACHE_HADOOP',
    'Apache Hadoop',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('APACHE_HBASE', 'Apache HBase', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_HIVE', 'Apache Hive', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_HUDI', 'Apache Hudi', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'APACHE_ICEBERG',
    'Apache Iceberg',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('APACHE_KAFKA', 'Apache Kafka', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_NIFI', 'Apache NiFi', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_OOZIE', 'Apache Oozie', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'APACHE_PARQUET',
    'Apache Parquet',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('APACHE_PINOT', 'Apache Pinot', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'APACHE_PULSAR',
    'Apache Pulsar',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry(
    'APACHE_RANGER',
    'Apache Ranger',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('APACHE_SOLR', 'Apache Solr', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_SPARK', 'Apache Spark', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('APACHE_SQOOP', 'Apache Sqoop', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'ATLASSIAN_BAMBOO',
    'Atlassian Bamboo',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('AWS_GLUE', 'AWS Glue', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'AZURE_DATABRICKS',
    'Azure Databricks',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('DAGSTER', 'Dagster', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('DATABRICKS', 'Databricks', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('DEBEZIUM', 'Debezium', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('DELTA_LAKE', 'Delta Lake', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('FIVETRAN', 'Fivetran', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry(
    'GOOGLE_BIGQUERY',
    'Google BigQuery',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry(
    'KAFKA_CONNECT',
    'Kafka Connect',
    'DATA_ENGINEERING_BIG_DATA',
    'Data Engineering & Big Data',
  ),
  entry('PREFECT', 'Prefect', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('PRESTO', 'Presto', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('SNOWFLAKE', 'Snowflake', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('TRINO', 'Trino', 'DATA_ENGINEERING_BIG_DATA', 'Data Engineering & Big Data'),
  entry('AGENTFORCE', 'Agentforce', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AIRBYTE', 'Airbyte', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('ANTHROPIC_API', 'Anthropic API', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('APACHE_AIRFLOW', 'Apache Airflow', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AUTOGEN', 'AutoGen', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AUTOGPT', 'AutoGPT', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AWS_CLOUDTRAIL', 'AWS CloudTrail', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AXOLOTL', 'Axolotl', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AZURE_AI_FOUNDRY', 'Azure AI Foundry', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'AZURE_CONTAINER_APPS',
    'Azure Container Apps',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'AZURE_CONTAINER_INSTANCES',
    'Azure Container Instances',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'AZURE_CONTAINER_REGISTRY',
    'Azure Container Registry',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'AZURE_OPENAI_SERVICE',
    'Azure OpenAI Service',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('BENTOML', 'BentoML', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('BULLMQ', 'BullMQ', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('CATBOOST', 'CatBoost', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('CONTAINERD', 'Containerd', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('CREWAI', 'CrewAI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('CUDA', 'CUDA', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('CUDA_Q', 'CUDA-Q', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('DETECTRON2', 'Detectron2', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('DSPY', 'DSPy', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('FAISS', 'FAISS', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('GENSIM', 'Gensim', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'GOOGLE_AGENT_DEVELOPMENT_KIT_ADK',
    'Google Agent Development Kit (ADK)',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('GOOGLE_GEMINI_API', 'Google Gemini API', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('GOOGLE_VERTEX_AI', 'Google Vertex AI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('HTML', 'HTML', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('HUGGING_FACE_HUB', 'Hugging Face Hub', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'HUGGING_FACE_TOKENIZERS',
    'Hugging Face Tokenizers',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'HUGGING_FACE_TRANSFORMERS',
    'Hugging Face Transformers',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('HUGGING_FACE_TRL', 'Hugging Face TRL', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('JOOMLA', 'Joomla', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('JOTAI', 'Jotai', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('KERAS', 'Keras', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LANGCHAIN', 'LangChain', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LANGGRAPH', 'LangGraph', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LIGHTGBM', 'LightGBM', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LLAMA_CPP', 'Llama.cpp', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LLAMAINDEX', 'LlamaIndex', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LORA', 'LoRA', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'MICROSOFT_SEMANTIC_KERNEL',
    'Microsoft Semantic Kernel',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('MLFLOW', 'MLflow', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('NLTK', 'NLTK', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('NUMPY', 'NumPy', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('NVIDIA_TENSORRT', 'NVIDIA TensorRT', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'NVIDIA_TENSORRT_LLM',
    'NVIDIA TensorRT-LLM',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('OLLAMA', 'Ollama', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('OPENAI_AGENTS_SDK', 'OpenAI Agents SDK', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('OPENAI_API', 'OpenAI API', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('OPENAI_CODEX', 'OpenAI Codex', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('OPENCV', 'OpenCV', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('OPENMMLAB', 'OpenMMLab', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('PANDAS', 'Pandas', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('PEFT', 'PEFT', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('PYDANTICAI', 'PydanticAI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('PYTORCH', 'PyTorch', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('PYTORCH_LIGHTNING', 'PyTorch Lightning', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('RAY', 'Ray', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('RAY_SERVE', 'Ray Serve', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('RUBY_ON_RAILS', 'Ruby on Rails', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('SAILPOINT', 'SailPoint', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('SCIKIT_LEARN', 'Scikit-learn', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('TAILWIND_CSS', 'Tailwind CSS', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('TENSORFLOW', 'TensorFlow', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('TESTCONTAINERS', 'Testcontainers', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('ULTRALYTICS_YOLO', 'Ultralytics YOLO', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('UNSLOTH', 'Unsloth', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('VERCEL_AI_SDK', 'Vercel AI SDK', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('VLLM', 'vLLM', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('XGBOOST', 'XGBoost', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'COMPUTER_VISION_ENGINEERING',
    'Computer Vision',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'DEEP_LEARNING_NEURAL_NETWORK_ENGINEERING',
    'Deep Learning',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('EMBEDDINGS', 'Embeddings', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'FEATURE_ENGINEERING',
    'Feature Engineering',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('GENERATIVE_AI', 'Generative AI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'INFORMATION_RETRIEVAL',
    'Information Retrieval',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('LLMS', 'LLMs', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('NATURAL_LANGUAGE_PROCESSING_NLP', 'NLP', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('STATISTICS', 'Statistics', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('VECTOR_DATABASES', 'Vector Databases', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('VECTOR_SEARCH', 'Vector Search', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('A_B_TESTING', 'A/B Testing', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AGENT_EVALUATION', 'Agent Evaluation', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'AGENT_ORCHESTRATION',
    'Agent Orchestration',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('AI_GUARDRAILS', 'AI Guardrails', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('ANTHROPIC_CLAUDE', 'Anthropic Claude', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('CLOUD_ML_PLATFORMS', 'Cloud ML Platforms', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('DATA_PIPELINES', 'Data Pipelines', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'EVALUATION_DATASETS',
    'Evaluation Datasets',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'INFERENCE_PIPELINES',
    'Inference Pipelines',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('ML_PIPELINES', 'ML Pipelines', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MLOPS_MODEL_LIFECYCLE_MANAGEMENT', 'MLOps', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_DEPLOYMENT', 'Model Deployment', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_MONITORING', 'Model Monitoring', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_REGISTRY', 'Model Registry', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_SERVING', 'Model Serving', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_VERSIONING', 'Model Versioning', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('OPENAI_APIS', 'OpenAI APIs', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('REGRESSION_TESTING', 'Regression Testing', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('SEMANTIC_SEARCH', 'Semantic Search', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'STRUCTURED_DATA_EXTRACTION',
    'Structured Data Extraction',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'MODEL_CONTEXT_PROTOCOL_MCP',
    'Model Context Protocol (MCP)',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('SKILL_3D_VISION', '3D Vision', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AGENT_GUARDRAILS', 'Agent Guardrails', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'AGENT_OBSERVABILITY',
    'Agent Observability',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('AGENTIC_WORKFLOW', 'Agentic Workflow', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AI_OBSERVABILITY', 'AI Observability', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AI_SAFETY_TESTING', 'AI Safety Testing', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'COST_LATENCY_EVALUATION',
    'Cost / Latency Evaluation',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry(
    'DISTRIBUTED_TRAINING',
    'Distributed Training',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('EDGE_AI', 'Edge AI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('GPU_INFRASTRUCTURE', 'GPU Infrastructure', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('GPU_OPTIMIZATION', 'GPU Optimization', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('GPU_SCHEDULING', 'GPU Scheduling', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('HYBRID_SEARCH', 'Hybrid Search', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LLM_APPLICATIONS', 'LLM Applications', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LLM_EVALUATION', 'LLM Evaluation', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('LLM_OBSERVABILITY', 'LLM Observability', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'LLM_REGRESSION_TESTING',
    'LLM Regression Testing',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('LLM_AS_A_JUDGE', 'LLM-as-a-Judge', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'MODEL_BEHAVIOR_MONITORING',
    'Model Behavior Monitoring',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('MODEL_CALIBRATION', 'Model Calibration', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_DRIFT', 'Model Drift', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_FALLBACKS', 'Model Fallbacks', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('MODEL_ROUTING', 'Model Routing', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'MULTI_AGENT_SYSTEMS',
    'Multi-Agent Systems',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('MULTIMODAL_AI', 'Multimodal AI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('RESPONSIBLE_AI', 'Responsible AI', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry(
    'RETRIEVAL_RERANKING',
    'Retrieval Reranking',
    'AI_ML_DATA_SCIENCE',
    'AI, ML & Data Science',
  ),
  entry('SEMANTIC_RETRIEVAL', 'Semantic Retrieval', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('STEREO_VISION', 'Stereo Vision', 'AI_ML_DATA_SCIENCE', 'AI, ML & Data Science'),
  entry('AMASS', 'Amass', 'CYBERSECURITY', 'Cybersecurity'),
  entry('AWS_SECRETS_MANAGER', 'AWS Secrets Manager', 'CYBERSECURITY', 'Cybersecurity'),
  entry('BETTERCAP', 'Bettercap', 'CYBERSECURITY', 'Cybersecurity'),
  entry('BLOODHOUND', 'BloodHound', 'CYBERSECURITY', 'Cybersecurity'),
  entry('BURP_SUITE', 'Burp Suite', 'CYBERSECURITY', 'Cybersecurity'),
  entry('CROWDSTRIKE_FALCON', 'CrowdStrike Falcon', 'CYBERSECURITY', 'Cybersecurity'),
  entry('CYBERARK', 'CyberArk', 'CYBERSECURITY', 'Cybersecurity'),
  entry('ELASTIC_SECURITY', 'Elastic Security', 'CYBERSECURITY', 'Cybersecurity'),
  entry('FRIDA', 'Frida', 'CYBERSECURITY', 'Cybersecurity'),
  entry(
    'GOOGLE_CLOUD_SECRET_MANAGER',
    'Google Cloud Secret Manager',
    'CYBERSECURITY',
    'Cybersecurity',
  ),
  entry('HASHCAT', 'Hashcat', 'CYBERSECURITY', 'Cybersecurity'),
  entry('IDA_PRO', 'IDA Pro', 'CYBERSECURITY', 'Cybersecurity'),
  entry('KALI_LINUX', 'Kali Linux', 'CYBERSECURITY', 'Cybersecurity'),
  entry('METASPLOIT', 'Metasploit', 'CYBERSECURITY', 'Cybersecurity'),
  entry('MICROSOFT_DEFENDER', 'Microsoft Defender', 'CYBERSECURITY', 'Cybersecurity'),
  entry(
    'MICROSOFT_DEFENDER_FOR_CLOUD',
    'Microsoft Defender for Cloud',
    'CYBERSECURITY',
    'Cybersecurity',
  ),
  entry(
    'MICROSOFT_DEFENDER_FOR_ENDPOINT',
    'Microsoft Defender for Endpoint',
    'CYBERSECURITY',
    'Cybersecurity',
  ),
  entry('MICROSOFT_INTUNE', 'Microsoft Intune', 'CYBERSECURITY', 'Cybersecurity'),
  entry('MICROSOFT_PURVIEW', 'Microsoft Purview', 'CYBERSECURITY', 'Cybersecurity'),
  entry('MICROSOFT_SENTINEL', 'Microsoft Sentinel', 'CYBERSECURITY', 'Cybersecurity'),
  entry('NESSUS', 'Nessus', 'CYBERSECURITY', 'Cybersecurity'),
  entry('NIKTO', 'Nikto', 'CYBERSECURITY', 'Cybersecurity'),
  entry('NMAP', 'Nmap', 'CYBERSECURITY', 'Cybersecurity'),
  entry('OKTA', 'Okta', 'CYBERSECURITY', 'Cybersecurity'),
  entry('OPENVAS', 'OpenVAS', 'CYBERSECURITY', 'Cybersecurity'),
  entry('OWASP_ZAP', 'OWASP ZAP', 'CYBERSECURITY', 'Cybersecurity'),
  entry(
    'PALO_ALTO_NETWORKS_CORTEX_XDR',
    'Palo Alto Networks Cortex XDR',
    'CYBERSECURITY',
    'Cybersecurity',
  ),
  entry('PALO_ALTO_NETWORKS_PAN_OS', 'Palo Alto Networks PAN-OS', 'CYBERSECURITY', 'Cybersecurity'),
  entry(
    'PALO_ALTO_NETWORKS_PRISMA_CLOUD',
    'Palo Alto Networks Prisma Cloud',
    'CYBERSECURITY',
    'Cybersecurity',
  ),
  entry('PRISMA', 'Prisma', 'CYBERSECURITY', 'Cybersecurity'),
  entry('QUALYS', 'Qualys', 'CYBERSECURITY', 'Cybersecurity'),
  entry('RADARE2', 'Radare2', 'CYBERSECURITY', 'Cybersecurity'),
  entry('RAPID7', 'Rapid7', 'CYBERSECURITY', 'Cybersecurity'),
  entry('SNORT', 'Snort', 'CYBERSECURITY', 'Cybersecurity'),
  entry('SPRING_SECURITY', 'Spring Security', 'CYBERSECURITY', 'Cybersecurity'),
  entry('SURICATA', 'Suricata', 'CYBERSECURITY', 'Cybersecurity'),
  entry('TENABLE', 'Tenable', 'CYBERSECURITY', 'Cybersecurity'),
  entry('WAZUH', 'Wazuh', 'CYBERSECURITY', 'Cybersecurity'),
  entry('WIRESHARK', 'Wireshark', 'CYBERSECURITY', 'Cybersecurity'),
  entry('JWT', 'JWT', 'CYBERSECURITY', 'Cybersecurity'),
  entry('LDAP', 'LDAP', 'CYBERSECURITY', 'Cybersecurity'),
  entry('OAUTH_2_0', 'OAuth 2.0', 'CYBERSECURITY', 'Cybersecurity'),
  entry('OPENID_CONNECT', 'OpenID Connect', 'CYBERSECURITY', 'Cybersecurity'),
  entry('AI_GOVERNANCE', 'AI Governance', 'CYBERSECURITY', 'Cybersecurity'),
  entry('DATA_GOVERNANCE', 'Data Governance', 'CYBERSECURITY', 'Cybersecurity'),
  entry('PII_REDACTION', 'PII Redaction', 'CYBERSECURITY', 'Cybersecurity'),
  entry('APPIUM', 'Appium', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('ASSERTJ', 'AssertJ', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('CAPYBARA', 'Capybara', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('CUCUMBER', 'Cucumber', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('CYPRESS', 'Cypress', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('DETOX', 'Detox', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('ESPRESSO', 'Espresso', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('GATLING', 'Gatling', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('GOOGLE_TEST', 'Google Test', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('JASMINE', 'Jasmine', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('JBEHAVE', 'JBehave', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('JEST', 'Jest', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('JMETER', 'JMeter', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('JUNIT', 'JUnit', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('K6', 'K6', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('KARATE', 'Karate', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('LOCUST', 'Locust', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('MOCHA', 'Mocha', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('MOCKITO', 'Mockito', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('MSTEST', 'MSTest', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('NEWMAN', 'Newman', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('NUNIT', 'NUnit', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('PACT', 'Pact', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('PLAYWRIGHT', 'Playwright', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('POSTMAN', 'Postman', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('PYTEST', 'Pytest', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry(
    'REACT_NATIVE_TESTING_LIBRARY',
    'React Native Testing Library',
    'TESTING_QA_RELIABILITY',
    'Testing, QA & Reliability',
  ),
  entry(
    'REACT_TESTING_LIBRARY',
    'React Testing Library',
    'TESTING_QA_RELIABILITY',
    'Testing, QA & Reliability',
  ),
  entry(
    'ROBOT_FRAMEWORK',
    'Robot Framework',
    'TESTING_QA_RELIABILITY',
    'Testing, QA & Reliability',
  ),
  entry('RSPEC', 'RSpec', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('SELENIUM', 'Selenium', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('SUPERTEST', 'Supertest', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('TESTNG', 'TestNG', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('VITEST', 'Vitest', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('WIREMOCK', 'WireMock', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('XCTEST', 'XCTest', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('XUNIT', 'xUnit', 'TESTING_QA_RELIABILITY', 'Testing, QA & Reliability'),
  entry('ANDROID_SDK', 'Android SDK', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('ANDROID_STUDIO', 'Android Studio', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('BLOC_FLUTTER', 'Bloc (Flutter)', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('CAPACITOR', 'Capacitor', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('CISCO_IOS', 'Cisco IOS', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('CORE_DATA', 'Core Data', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('DAGGER_ANDROID_DI', 'Dagger (Android DI)', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('EXPO', 'Expo', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('FASTLANE', 'Fastlane', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('FLUTTER', 'Flutter', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('GETX', 'GetX', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('IONIC', 'Ionic', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('JETPACK_COMPOSE', 'Jetpack Compose', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('OKHTTP', 'OkHttp', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('PROVIDER_FLUTTER', 'Provider (Flutter)', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('REACT_NATIVE', 'React Native', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('REALM', 'Realm', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('RETROFIT', 'Retrofit', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('RIVERPOD', 'Riverpod', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('SWIFTUI', 'SwiftUI', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('UIKIT', 'UIKit', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('ANDROID_JETPACK', 'Android Jetpack', 'MOBILE_DEVELOPMENT', 'Mobile Development'),
  entry('ALPINE_JS', 'Alpine.js', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ANGULAR', 'Angular', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry(
    'ANGULAR_MATERIAL',
    'Angular Material',
    'FRONTEND_WEB_DEVELOPMENT',
    'Frontend & Web Development',
  ),
  entry('ANGULARJS', 'AngularJS', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ANT_DESIGN', 'Ant Design', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ASTRO', 'Astro', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('BABEL', 'Babel', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('BOOTSTRAP', 'Bootstrap', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('CHAKRA_UI', 'Chakra UI', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('CSS', 'CSS', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('D3_JS', 'D3.js', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ERPNEXT', 'ERPNext', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ESBUILD', 'esbuild', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ESLINT', 'ESLint', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('FORMIK', 'Formik', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('HTMX', 'HTMX', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('MATERIAL_UI', 'Material UI', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('MOBX', 'MobX', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('NEXT_JS', 'Next.js', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('NUXT_JS', 'Nuxt.js', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('PINIA', 'Pinia', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('PRIMENG', 'PrimeNG', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('REACT', 'React', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry(
    'REACT_NAVIGATION',
    'React Navigation',
    'FRONTEND_WEB_DEVELOPMENT',
    'Frontend & Web Development',
  ),
  entry('REACT_ROUTER', 'React Router', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('REDUX', 'Redux', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('REDUX_THUNK', 'Redux Thunk', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('REDUX_TOOLKIT', 'Redux Toolkit', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('REMIX', 'Remix', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('RXJS', 'RxJS', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('SASS', 'Sass', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('SHADCN_UI', 'shadcn/ui', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('STORYBOOK', 'Storybook', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('SVELTE', 'Svelte', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('SVELTEKIT', 'SvelteKit', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('SWC', 'SWC', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry(
    'TANSTACK_QUERY',
    'TanStack Query',
    'FRONTEND_WEB_DEVELOPMENT',
    'Frontend & Web Development',
  ),
  entry(
    'TANSTACK_ROUTER',
    'TanStack Router',
    'FRONTEND_WEB_DEVELOPMENT',
    'Frontend & Web Development',
  ),
  entry('THREE_JS', 'Three.js', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('VITE', 'Vite', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('VUE_ROUTER', 'Vue Router', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('VUE_JS', 'Vue.js', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('WEBPACK', 'Webpack', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry('ZUSTAND', 'Zustand', 'FRONTEND_WEB_DEVELOPMENT', 'Frontend & Web Development'),
  entry(
    'CISCO_NX_OS',
    'Cisco NX-OS',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'COREDNS',
    'CoreDNS',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'DEBIAN',
    'Debian',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'FEDORA',
    'Fedora',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'HYPER_V',
    'Hyper-V',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry('KVM', 'KVM', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry(
    'LINUX',
    'Linux',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'OPENVPN',
    'OpenVPN',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry('QEMU', 'QEMU', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry(
    'SONIC',
    'SONiC',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'SYSTEMD',
    'Systemd',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry('TMUX', 'tmux', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry(
    'UBUNTU',
    'Ubuntu',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'VMWARE_ESXI',
    'VMware ESXi',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'VMWARE_GEMFIRE',
    'VMware GemFire',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'VMWARE_VSPHERE',
    'VMware vSphere',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'WINDOWS_SERVER',
    'Windows Server',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'WIREGUARD',
    'WireGuard',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry('AMQP', 'AMQP', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry(
    'MODBUS',
    'Modbus',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry('MQTT', 'MQTT', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry('SFTP', 'SFTP', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry('SSH', 'SSH', 'NETWORKING_SYSTEMS_ADMINISTRATION', 'Networking & Systems Administration'),
  entry(
    'WEBASSEMBLY',
    'WebAssembly',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'WEBSOCKETS',
    'WebSockets',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry(
    'EVALUATION_HARNESSES',
    'Evaluation Harnesses',
    'NETWORKING_SYSTEMS_ADMINISTRATION',
    'Networking & Systems Administration',
  ),
  entry('ARDUINO', 'Arduino', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('ARDUPILOT', 'ArduPilot', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('BABYLON_JS', 'Babylon.js', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('CIRQ', 'Cirq', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('CRYENGINE', 'CryEngine', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('FREERTOS', 'FreeRTOS', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('GODOT', 'Godot', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('HYPERLEDGER_BESU', 'Hyperledger Besu', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('HYPERLEDGER_FABRIC', 'Hyperledger Fabric', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('MICROSOFT_DATAVERSE', 'Microsoft Dataverse', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('MICROSOFT_ENTRA_ID', 'Microsoft Entra ID', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('MICROSOFT_FABRIC', 'Microsoft Fabric', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry(
    'MICROSOFT_POWER_APPS',
    'Microsoft Power Apps',
    'EMERGING_TECHNOLOGY',
    'Emerging Technology',
  ),
  entry(
    'MICROSOFT_POWER_AUTOMATE',
    'Microsoft Power Automate',
    'EMERGING_TECHNOLOGY',
    'Emerging Technology',
  ),
  entry('MICROSTRATEGY', 'MicroStrategy', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('NVIDIA_ISAAC_ROS', 'NVIDIA Isaac ROS', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('OPENXR', 'OpenXR', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('PHASER', 'Phaser', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('PX4', 'PX4', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('QISKIT', 'Qiskit', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('ROS', 'ROS', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('ROS_2', 'ROS 2', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('STM32', 'STM32', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('THREADX', 'ThreadX', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('TRUFFLE', 'Truffle', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('UNITY', 'Unity', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('UNREAL_ENGINE', 'Unreal Engine', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('VULKAN', 'Vulkan', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('WEBGL', 'WebGL', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('WEBGPU', 'WebGPU', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('WEBXR', 'WebXR', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('ZEPHYR', 'Zephyr', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('ETHEREUM', 'Ethereum', 'EMERGING_TECHNOLOGY', 'Emerging Technology'),
  entry('BAZEL', 'Bazel', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry(
    'BITBUCKET_PIPELINES',
    'Bitbucket Pipelines',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry('CMAKE', 'CMake', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('COMPOSER', 'Composer', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('CONFLUENCE', 'Confluence', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('GERRIT', 'Gerrit', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('GIT', 'Git', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('GITEA', 'Gitea', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry(
    'GITHUB_COPILOT',
    'GitHub Copilot',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry('GRADLE', 'Gradle', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry(
    'INTELLIJ_IDEA',
    'IntelliJ IDEA',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry(
    'JFROG_ARTIFACTORY',
    'JFrog Artifactory',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry('MAVEN', 'Maven', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('NPM', 'npm', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('NUGET', 'NuGet', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('NX', 'Nx', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('ONNX', 'ONNX', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('ONNX_RUNTIME', 'ONNX Runtime', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('PNPM', 'pnpm', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('POETRY', 'Poetry', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('PYCHARM', 'PyCharm', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('QNX', 'QNX', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('RIDER', 'Rider', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry(
    'SONATYPE_NEXUS_REPOSITORY',
    'Sonatype Nexus Repository',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry('SUBVERSION', 'Subversion', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('TEAMCITY', 'TeamCity', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('TURBOREPO', 'Turborepo', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry(
    'VISUAL_STUDIO',
    'Visual Studio',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry(
    'VISUAL_STUDIO_CODE',
    'Visual Studio Code',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry('XCODE', 'Xcode', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('BITBUCKET', 'Bitbucket', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('GITHUB', 'GitHub', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('GITLAB', 'GitLab', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('JIRA', 'Jira', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry(
    'MICROSOFT_DYNAMICS_365',
    'Microsoft Dynamics 365',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry(
    'MICROSOFT_TEAMS',
    'Microsoft Teams',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry(
    'PYPI_PYTHON_PACKAGE_INDEX',
    'PyPI (Python Package Index)',
    'DELIVERY_PROCESS_TOOLING',
    'Delivery, Process & Tooling',
  ),
  entry('SALESFORCE', 'Salesforce', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('SERVICENOW', 'ServiceNow', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('SLACK', 'Slack', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
  entry('WORKDAY', 'Workday', 'DELIVERY_PROCESS_TOOLING', 'Delivery, Process & Tooling'),
] as const;

export const SKILL_CODES = SKILL_DEFINITIONS.map((skill) => skill.code);
export const SKILL_CODE_SET: ReadonlySet<string> = new Set(SKILL_CODES);

export interface SkillCategoryGroup {
  readonly id: SkillCategoryId;
  readonly name: string;
  readonly skills: readonly SkillDefinition[];
}

export function groupSkillsByCategory(): readonly SkillCategoryGroup[] {
  return SKILL_CATEGORY_IDS.map((id) => ({
    id,
    name: SKILL_CATEGORIES[id].name,
    skills: SKILL_DEFINITIONS.filter((skill) => skill.categoryId === id),
  }));
}

export function getSkillDefinition(code: string): SkillDefinition | undefined {
  return SKILL_DEFINITIONS.find((skill) => skill.code === code);
}
